# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inputs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('school', models.CharField(max_length=30)),
                ('email_id', models.EmailField(max_length=20)),
                ('password', models.CharField(max_length=15)),
                ('dateofbirth', models.DateField(max_length=8)),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')])),
                ('facebook', models.CharField(max_length=30)),
                ('score', models.IntegerField(default=1)),
            ],
        ),
    ]
